import { afterEach, describe, expect, it } from "vitest";
import { createApp } from "../src/app.js"; import { containsContactInformation } from "../src/schemas/tutor-cv.js"; import { testConfig } from "./helpers/config.js"; import { FakeAuthService } from "./helpers/fake-auth-service.js"; import { FakeTutorCvService } from "./helpers/fake-tutor-cv-service.js";
const userId="11111111-1111-4111-8111-111111111111", token="secret-token"; const apps:any[]=[];
function setup(role:"student"|"tutor"|"admin"="tutor") { const auth=new FakeAuthService(); auth.authentication={status:"authenticated",user:{id:userId,email:null}}; auth.profile={status:"found",profile:{id:userId,role,name:"Tutor",phone:null,avatar_url:null,created_at:"2026-01-01T00:00:00Z",updated_at:"2026-01-01T00:00:00Z"}}; const cv=new FakeTutorCvService(); const app=createApp({config:testConfig,authService:auth,tutorCvService:cv}); apps.push(app); return {app,cv}; }
afterEach(async()=>Promise.all(apps.splice(0).map(a=>a.close())));
const profile={displayName:"Nguyen Minh Anh",headline:"Mathematics tutor",bio:"A".repeat(100),hourlyRateVnd:300000,currency:"VND",teachingFormat:"online",subjects:["mathematics"],levels:["lower_secondary"],regions:[],languages:[{code:"vi",displayName:"Vietnamese",proficiency:"native"}],availability:[{dayOfWeek:1,startTime:"18:00",endTime:"20:00",timezone:"Asia/Ho_Chi_Minh"}],education:[],experience:[]};
describe("tutor CV routes",()=>{
 it("requires authentication",async()=>{const {app}=setup(); const r=await app.inject({method:"GET",url:"/api/v1/me/tutor-cv"}); expect(r.statusCode).toBe(401)});
 it("requires protected tutor role",async()=>{const {app,cv}=setup("student"); const r=await app.inject({method:"GET",url:"/api/v1/me/tutor-cv",headers:{authorization:`Bearer ${token}`}}); expect(r.statusCode).toBe(403); expect(cv.calls).toHaveLength(0)});
 it("returns own profile with no-store",async()=>{const {app,cv}=setup(); cv.result={status:"ok",data:null}; const r=await app.inject({method:"GET",url:"/api/v1/me/tutor-cv",headers:{authorization:`Bearer ${token}`}}); expect(r.json()).toEqual({ok:true,profile:null}); expect(r.headers["cache-control"]).toBe("no-store")});
 it("saves a valid draft without accepting ownership fields",async()=>{const {app,cv}=setup(); cv.result={status:"ok",data:{version:1}}; const r=await app.inject({method:"PUT",url:"/api/v1/me/tutor-cv",headers:{authorization:`Bearer ${token}`},payload:{expectedVersion:null,profile}}); expect(r.statusCode).toBe(200); expect(cv.calls[0]!.args[1]).not.toHaveProperty("userId")});
 it("rejects unknown fields",async()=>{const {app,cv}=setup(); const r=await app.inject({method:"PUT",url:"/api/v1/me/tutor-cv",headers:{authorization:`Bearer ${token}`},payload:{expectedVersion:null,profile:{...profile,userId:userId}}}); expect(r.statusCode).toBe(400); expect(cv.calls).toHaveLength(0)});
 it.each(["email me at tutor@example.com","Call +84 901 234 567","Visit https://example.com","www.example.com","Message Zalo","Whats App me","telegram @teacher","Find @teacher_name"])("blocks contact attempt: %s",async bio=>{const {app}=setup(); const r=await app.inject({method:"PUT",url:"/api/v1/me/tutor-cv",headers:{authorization:`Bearer ${token}`},payload:{expectedVersion:null,profile:{...profile,bio}}}); expect(r.statusCode).toBe(400); expect(r.json().error.code).toBe("CONTACT_INFORMATION_NOT_ALLOWED"); expect(r.body).not.toContain(bio)});
 it("accepts ordinary prose",()=>expect(containsContactInformation("I teach algebra with patient, structured examples.")).toBe(false));
 it("maps stale versions safely",async()=>{const {app,cv}=setup(); cv.result={status:"conflict"}; const r=await app.inject({method:"POST",url:"/api/v1/me/tutor-cv/publish",headers:{authorization:`Bearer ${token}`},payload:{expectedVersion:2}}); expect(r.statusCode).toBe(409); expect(r.json().error.code).toBe("PROFILE_VERSION_CONFLICT")});
 it("maps incomplete publication",async()=>{const {app,cv}=setup(); cv.result={status:"incomplete"}; const r=await app.inject({method:"POST",url:"/api/v1/me/tutor-cv/publish",headers:{authorization:`Bearer ${token}`},payload:{expectedVersion:2}}); expect(r.statusCode).toBe(422)});
});
