import { describe, expect, it, vi } from "vitest"; import { createApiClient } from "../../src/auth/api-client.js";
const profile = { id: "11111111-1111-4111-8111-111111111111", email: "user@example.com", role: "student", name: "User", phone: null, avatarUrl: null, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" };
const response = (status, body) => ({ ok: status >= 200 && status < 300, status, json: vi.fn().mockResolvedValue(body) });
describe("/me API client", () => {
  it("sends bearer only in the header with no credentials or cache", async () => { const fetchImpl = vi.fn().mockResolvedValue(response(200, { ok: true, user: profile })); const result = await createApiClient({ apiBaseUrl: "https://api.test", fetchImpl }).getMe("test-token"); expect(result.role).toBe("student"); const [url, init] = fetchImpl.mock.calls[0]; expect(url).toBe("https://api.test/api/v1/me"); expect(url).not.toContain("test-token"); expect(init).toMatchObject({ cache: "no-store", credentials: "omit", headers: { Authorization: "Bearer test-token" } }); });
  it.each([[401, "UNAUTHORIZED"], [403, "FORBIDDEN"], [404, "PROFILE_NOT_FOUND"], [429, "RATE_LIMITED"], [503, "SERVICE_UNAVAILABLE"], [500, "INTERNAL_ERROR"]])("maps %s safely", async (status, code) => { const client = createApiClient({ apiBaseUrl: "https://api.test", fetchImpl: vi.fn().mockResolvedValue(response(status, { error: { message: "raw database secret" } })) }); await expect(client.getMe("hidden-token")).rejects.toMatchObject({ code }); await expect(client.getMe("hidden-token")).rejects.not.toThrow("hidden-token"); });
  it("rejects malformed JSON", async () => { const client = createApiClient({ apiBaseUrl: "https://api.test", fetchImpl: vi.fn().mockResolvedValue({ ok: true, status: 200, json: vi.fn().mockRejectedValue(new Error("html")) }) }); await expect(client.getMe("x")).rejects.toMatchObject({ code: "INVALID_RESPONSE" }); });
  it.each([{ ...profile, id: "bad" }, { ...profile, role: "owner" }, { ...profile, createdAt: "yesterday" }])("rejects malformed profiles", async (user) => { const client = createApiClient({ apiBaseUrl: "https://api.test", fetchImpl: vi.fn().mockResolvedValue(response(200, { ok: true, user })) }); await expect(client.getMe("x")).rejects.toMatchObject({ code: "INVALID_PROFILE" }); });
  it("maps network errors without leaking tokens", async () => { const client = createApiClient({ apiBaseUrl: "https://api.test", fetchImpl: vi.fn().mockRejectedValue(new Error("network hidden-token")) }); await expect(client.getMe("hidden-token")).rejects.toMatchObject({ code: "NETWORK_ERROR" }); });
});
