import { beforeEach, describe, expect, it, vi } from "vitest"; import { createAuthUI } from "../../src/auth-ui/auth-ui.js";
function setup(state = { status: "anonymous", profile: null }) { const authService = { signUp: vi.fn().mockResolvedValue({ session: null, error: null }), signIn: vi.fn(), resendVerification: vi.fn(), requestPasswordReset: vi.fn(), completePasswordRecovery: vi.fn(), signOut: vi.fn() }; const manager = { getState: vi.fn(() => state), synchronize: vi.fn(), invalidate: vi.fn() }; const navigate = vi.fn(); return { ui: createAuthUI({ authService, manager, navigate }), authService, manager, navigate }; }
const tick = () => new Promise((resolve) => setTimeout(resolve, 0));
describe("authentication UI", () => {
  beforeEach(() => { document.body.replaceChildren(); });
  it("renders signup with no admin option and safe controls", () => { const { ui } = setup(); ui.render(document.body, "#/auth/sign-up", { status: "anonymous" }); expect(document.querySelector('option[value="admin"]')).toBeNull(); expect(document.querySelector('input[autocomplete="new-password"]')).not.toBeNull(); expect(document.body.textContent).toContain("Privacy Policy"); });
  it("submits student signup and routes to check-email without private UI", async () => { const { ui, authService, navigate } = setup(); ui.render(document.body, "#/auth/sign-up", { status: "anonymous" }); const form = document.querySelector("form"); form.elements.name.value = " Student "; form.elements.email.value = "student@example.com"; form.elements.password.value = form.elements.confirmPassword.value = "a secure password"; form.elements.role.value = "student"; form.elements.terms.checked = true; form.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })); await tick(); expect(authService.signUp.mock.calls[0][0].role).toBe("student"); expect(navigate).toHaveBeenCalledWith("#/auth/check-email"); expect(form.elements.password.value).toBe(""); });
  it("prevents duplicate submission while pending", async () => { let resolve; const { ui, authService } = setup(); authService.requestPasswordReset.mockReturnValue(new Promise((done) => { resolve = done; })); ui.render(document.body, "#/auth/forgot-password", { status: "anonymous" }); const form = document.querySelector("form"); form.elements.email.value = "user@example.com"; form.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })); form.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })); expect(authService.requestPasswordReset).toHaveBeenCalledOnce(); resolve(); await tick(); });
  it("does not render provider error or a token", async () => { const { ui, authService } = setup(); authService.signIn.mockResolvedValue({ data: null, error: new Error("provider hidden-token details") }); ui.render(document.body, "#/auth/sign-in", { status: "anonymous" }); const form = document.querySelector("form"); form.elements.email.value = "user@example.com"; form.elements.password.value = "hidden-password"; form.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })); await tick(); expect(document.body.textContent).toContain("Unable to sign in"); expect(document.body.textContent).not.toMatch(/hidden-token|hidden-password|provider/); expect(form.elements.password.value).toBe(""); });
  it("requires genuine recovery state", () => { const { ui } = setup(); ui.render(document.body, "#/auth/update-password", { status: "anonymous" }); expect(document.querySelector('input[type="password"]')).toBeNull(); expect(document.body.textContent).toContain("invalid or expired"); });
});
