import { describe, expect, it, vi } from "vitest"; import { createAuthService } from "../../src/auth/auth-service.js";
function setup() { const auth = { signUp: vi.fn().mockResolvedValue({ data: { session: null }, error: null }), signInWithPassword: vi.fn().mockResolvedValue({ data: {}, error: null }), signOut: vi.fn(), resend: vi.fn(), resetPasswordForEmail: vi.fn(), updateUser: vi.fn(), exchangeCodeForSession: vi.fn() }; return { auth, service: createAuthService({ client: { auth }, callbackUrl: "https://app.test/auth/callback" }) }; }
const signup = { name: " User ", email: " user@example.com ", password: " password with spaces ", confirmPassword: " password with spaces ", role: "student", acceptedTerms: true };
describe("auth service", () => {
  it("sends only validated student metadata", async () => { const { auth, service } = setup(); await service.signUp(signup); expect(auth.signUp).toHaveBeenCalledWith({ email: "user@example.com", password: " password with spaces ", options: { data: { name: "User", role: "student" }, emailRedirectTo: "https://app.test/auth/callback" } }); });
  it("allows tutor signup", async () => { const { auth, service } = setup(); await service.signUp({ ...signup, role: "tutor" }); expect(auth.signUp.mock.calls[0][0].options.data.role).toBe("tutor"); });
  it.each(["admin", "unknown"])("rejects %s signup", async (role) => { const { auth, service } = setup(); await expect(service.signUp({ ...signup, role })).rejects.toThrow("INVALID_ROLE"); expect(auth.signUp).not.toHaveBeenCalled(); });
  it("trims sign-in email but not password", async () => { const { auth, service } = setup(); await service.signIn({ email: " user@example.com ", password: " password " }); expect(auth.signInWithPassword).toHaveBeenCalledWith({ email: "user@example.com", password: " password " }); });
  it("uses fixed verification and reset callbacks", async () => { const { auth, service } = setup(); await service.resendVerification("user@example.com"); await service.requestPasswordReset("user@example.com"); expect(auth.resend.mock.calls[0][0].options.emailRedirectTo).toBe("https://app.test/auth/callback"); expect(auth.resetPasswordForEmail).toHaveBeenCalledWith("user@example.com", { redirectTo: "https://app.test/auth/callback" }); });
  it("uses global logout", async () => { const { auth, service } = setup(); await service.signOut(); expect(auth.signOut).toHaveBeenCalledWith({ scope: "global" }); });
  it("does not trim recovered passwords", async () => { const { auth, service } = setup(); await service.completePasswordRecovery({ password: " password long ", confirmPassword: " password long " }); expect(auth.updateUser).toHaveBeenCalledWith({ password: " password long " }); });
});
