import { describe, expect, it, vi } from "vitest"; import { createSessionManager } from "../../src/auth/session-manager.js";
const session = { access_token: "test-token", user: { user_metadata: { role: "admin" } } }, profile = { id: "1", role: "student", name: "Trusted" };
function setup(initial = null) { let callback; const subscription = { unsubscribe: vi.fn() }; const auth = { getSession: vi.fn().mockResolvedValue({ data: { session: initial } }), onAuthStateChange: vi.fn((handler) => { callback = handler; return { data: { subscription } }; }), refreshSession: vi.fn(), signOut: vi.fn() }; const apiClient = { getMe: vi.fn().mockResolvedValue(profile) }; return { manager: createSessionManager({ client: { auth }, apiClient }), auth, apiClient, emit: (event, value) => callback(event, value), subscription }; }
describe("session manager", () => {
  it("restores anonymous state", async () => expect((await setup().manager.initialize()).status).toBe("anonymous"));
  it("restores a session through /me and ignores metadata role", async () => { const { manager, apiClient } = setup(session); const state = await manager.initialize(); expect(apiClient.getMe).toHaveBeenCalledWith("test-token"); expect(state.profile.role).toBe("student"); });
  it("initializes and subscribes only once", async () => { const { manager, auth } = setup(); await manager.initialize(); await manager.initialize(); expect(auth.onAuthStateChange).toHaveBeenCalledOnce(); });
  it("clears profile on logout event", async () => { const { manager, emit } = setup(session); await manager.initialize(); emit("SIGNED_OUT", null); await new Promise(queueMicrotask); expect(manager.getState().profile).toBeNull(); });
  it("synchronizes token refresh events", async () => { const { manager, emit, apiClient } = setup(); await manager.initialize(); emit("TOKEN_REFRESHED", session); await new Promise(queueMicrotask); await new Promise(queueMicrotask); expect(apiClient.getMe).toHaveBeenCalledWith("test-token"); });
  it("marks genuine password recovery", async () => { const { manager, emit } = setup(); await manager.initialize(); emit("PASSWORD_RECOVERY", session); expect(manager.getState().status).toBe("password_recovery"); });
  it("refreshes at most once after 401", async () => { const { manager, apiClient, auth } = setup(session); apiClient.getMe.mockRejectedValueOnce({ code: "UNAUTHORIZED" }).mockResolvedValue(profile); auth.refreshSession.mockResolvedValue({ data: { session } }); expect((await manager.initialize()).status).toBe("authenticated"); expect(auth.refreshSession).toHaveBeenCalledOnce(); expect(apiClient.getMe).toHaveBeenCalledTimes(2); });
  it("fails closed on service outage", async () => { const { manager, apiClient } = setup(session); apiClient.getMe.mockRejectedValue({ code: "SERVICE_UNAVAILABLE" }); const state = await manager.initialize(); expect(state).toMatchObject({ status: "service_unavailable", profile: null }); });
  it("fails closed when session restoration is unavailable", async () => { const { manager, auth } = setup(); auth.getSession.mockRejectedValue(new Error("provider detail")); expect(await manager.initialize()).toMatchObject({ status: "service_unavailable", profile: null, safeErrorCode: "SERVICE_UNAVAILABLE" }); });
  it("does not let stale /me overwrite logout", async () => { let resolve; const { manager, apiClient } = setup(); apiClient.getMe.mockReturnValue(new Promise((done) => { resolve = done; })); await manager.initialize(); const pending = manager.synchronize(session); manager.invalidate(); resolve(profile); await pending; expect(manager.getState().status).toBe("anonymous"); });
});
