import type { AppConfig } from "../../src/config/env.js";
export const testConfig: AppConfig = {
  NODE_ENV: "test", HOST: "127.0.0.1", PORT: 4000, FRONTEND_ORIGINS: ["https://frontend.test"],
  SUPABASE_URL: "https://project.supabase.co", SUPABASE_PUBLISHABLE_KEY: "test-publishable-key", VNPAY_PAYMENT_URL: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html", TRUST_PROXY: false,
  RATE_LIMIT_MAX: 100, RATE_LIMIT_WINDOW_MS: 60_000, ME_RATE_LIMIT_MAX: 30,
  TUTOR_CV_GET_RATE_LIMIT_MAX: 60, TUTOR_CV_SAVE_RATE_LIMIT_MAX: 20, TUTOR_CV_PUBLISH_RATE_LIMIT_MAX: 10,
  PUBLIC_TUTORS_LIST_RATE_LIMIT_MAX: 60, PUBLIC_TUTOR_DETAIL_RATE_LIMIT_MAX: 120,
  REQUEST_TIMEOUT_MS: 15_000, KEEP_ALIVE_TIMEOUT_MS: 5_000, BODY_LIMIT_BYTES: 16_384, MAX_AUTHORIZATION_HEADER_LENGTH: 100
};
