import { createClient } from "@supabase/supabase-js";
import type { ServiceResult, TutorCvService } from "../types/tutor-cv.js";
import { logServiceError } from "../lib/service-error.js";
const auth = { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } as const;
function mapError(error: { code?: string; message?: string } | null): ServiceResult<never> { const code = error?.code || "", message = error?.message || ""; if (code === "P0002") return { status: "not_found" }; if (code === "42501") return { status: "forbidden" }; if (code === "40001" || message.includes("PROFILE_VERSION_CONFLICT")) return { status: "conflict" }; if (message.includes("TUTOR_CV_INCOMPLETE")) return { status: "incomplete" }; if (code === "22023" || message.includes("TUTOR_CV_INVALID") || message.includes("CONTACT_INFORMATION_NOT_ALLOWED")) return { status: "invalid" }; return { status: "unavailable" }; }
export function createSupabaseTutorCvService(url: string, key: string): TutorCvService {
  async function rpc(name: string, params: Record<string, unknown>, token?: string): Promise<ServiceResult<unknown>> { try { const client = createClient(url, key, { auth, ...(token ? { global: { headers: { Authorization: `Bearer ${token}` } } } : {}) }); const { data, error } = await client.rpc(name, params); return error ? mapError(error) : { status: "ok", data }; } catch (error) { logServiceError({ service: "tutor-cv-service", operation: "rpc", error }); return { status: "unavailable" }; } }
  return { getOwn: (token) => rpc("get_my_tutor_cv", {}, token), saveOwn: (token, profile, expectedVersion) => rpc("save_my_tutor_cv", { payload: profile, expected_version: expectedVersion }, token), publishOwn: (token, expectedVersion) => rpc("publish_my_tutor_cv", { expected_version: expectedVersion }, token), unpublishOwn: (token, expectedVersion) => rpc("unpublish_my_tutor_cv", { expected_version: expectedVersion }, token), listPublic: (filters) => rpc("list_published_tutors", { filters }), getPublic: (id) => rpc("get_published_tutor", { tutor_profile_id: id }) };
}
