import type { FastifyPluginAsync } from "fastify";
import { ApiError } from "../errors/api-error.js";
import { containsContactInformation, saveTutorCvSchema, versionSchema } from "../schemas/tutor-cv.js";
import type { AuthService } from "../services/auth-service.js";
import type { ServiceResult, TutorCvService } from "../types/tutor-cv.js";
const noStore = async (_request: unknown, reply: any, payload: unknown) => { reply.header("Cache-Control", "no-store").header("Pragma", "no-cache"); return payload; };
function fail(result: ServiceResult<unknown>): never { if (result.status === "forbidden") throw new ApiError(403, "TUTOR_ROLE_REQUIRED", "A tutor account is required."); if (result.status === "not_found") throw new ApiError(404, "TUTOR_CV_NOT_FOUND", "Tutor CV was not found."); if (result.status === "conflict") throw new ApiError(409, "PROFILE_VERSION_CONFLICT", "This profile changed elsewhere. Reload it before saving."); if (result.status === "incomplete") throw new ApiError(422, "TUTOR_CV_INCOMPLETE", "Complete the required profile fields before publishing."); if (result.status === "invalid") throw new ApiError(400, "TUTOR_CV_INVALID", "Tutor CV data is invalid."); throw new ApiError(503, "SERVICE_UNAVAILABLE", "Tutor profile service is temporarily unavailable."); }
async function requireTutor(authService: AuthService, request: any) { const profile = await authService.getOwnProfile(request.auth.accessToken, request.auth.userId); if (profile.status === "unavailable") throw new ApiError(503, "SERVICE_UNAVAILABLE", "Profile service is temporarily unavailable."); if (profile.status !== "found" || profile.profile.id !== request.auth.userId || profile.profile.role !== "tutor") throw new ApiError(403, "TUTOR_ROLE_REQUIRED", "A tutor account is required."); }
export const tutorCvRoutes: FastifyPluginAsync<{ authService: AuthService; tutorCvService: TutorCvService; limits: { get: number; save: number; publish: number }; windowMs: number }> = async (app, options) => {
  const protectedRoute = (max: number) => ({ preHandler: app.authenticate, config: { rateLimit: { max, timeWindow: options.windowMs } }, onSend: noStore });
  app.get("/api/v1/me/tutor-cv", protectedRoute(options.limits.get), async (request) => { await requireTutor(options.authService, request); const result = await options.tutorCvService.getOwn(request.auth.accessToken); if (result.status !== "ok") fail(result); return { ok: true, profile: result.data }; });
  app.put("/api/v1/me/tutor-cv", protectedRoute(options.limits.save), async (request) => { await requireTutor(options.authService, request); const parsed = saveTutorCvSchema.safeParse(request.body); if (!parsed.success) throw new ApiError(400, "TUTOR_CV_INVALID", "Tutor CV data is invalid."); if (containsContactInformation(parsed.data.profile)) throw new ApiError(400, "CONTACT_INFORMATION_NOT_ALLOWED", "Public profiles cannot contain direct contact information."); const result = await options.tutorCvService.saveOwn(request.auth.accessToken, parsed.data.profile, parsed.data.expectedVersion); if (result.status !== "ok") fail(result); return { ok: true, profile: result.data }; });
  for (const action of ["publish", "unpublish"] as const) app.post(`/api/v1/me/tutor-cv/${action}`, protectedRoute(options.limits.publish), async (request) => { await requireTutor(options.authService, request); const parsed = versionSchema.safeParse(request.body); if (!parsed.success) throw new ApiError(400, "TUTOR_CV_INVALID", "Tutor CV data is invalid."); const result = action === "publish" ? await options.tutorCvService.publishOwn(request.auth.accessToken, parsed.data.expectedVersion) : await options.tutorCvService.unpublishOwn(request.auth.accessToken, parsed.data.expectedVersion); if (result.status !== "ok") fail(result); return { ok: true, profile: result.data }; });
};
