export class TutorCvApiError extends Error { constructor(code, status=0) { super(code); this.code=code; this.status=status; } }
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function createTutorCvApi({apiBaseUrl, getAccessToken, onUnauthorized=()=>{}, fetchImpl=fetch, timeoutMs=12000}) {
  async function request(path,{method="GET",body,authenticated=false}={}) { const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs); try { const headers={Accept:"application/json"}; if(body!==undefined) headers["Content-Type"]="application/json"; if(authenticated){const token=getAccessToken();if(!token)throw new TutorCvApiError("UNAUTHORIZED",401);headers.Authorization=`Bearer ${token}`;} const response=await fetchImpl(`${apiBaseUrl}${path}`,{method,headers,...(body===undefined?{}:{body:JSON.stringify(body)}),credentials:"omit",cache:"no-store",signal:controller.signal}); let payload;try{payload=await response.json()}catch{throw new TutorCvApiError("INVALID_RESPONSE",response.status)} if(!response.ok){const code=typeof payload?.error?.code==="string"?payload.error.code:"INTERNAL_ERROR";if(response.status===401)onUnauthorized();throw new TutorCvApiError(code,response.status)} if(payload?.ok!==true)throw new TutorCvApiError("INVALID_RESPONSE",response.status);return payload;}catch(error){if(error instanceof TutorCvApiError)throw error;throw new TutorCvApiError(error?.name==="AbortError"?"TIMEOUT":"NETWORK_ERROR")}finally{clearTimeout(timer)} }
  const query=(filters={})=>{const params=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>{if(value!==undefined&&value!==null&&value!=="")params.set(key,String(value))});return params.size?`?${params}`:""};
  const profileResponse=async promise=>{const value=await promise;if(value.profile!==null&&(typeof value.profile!=="object"||typeof value.profile.id!=="string"&&!Number.isInteger(value.profile.version)))throw new TutorCvApiError("INVALID_RESPONSE",500);return value};
  const listResponse=async promise=>{const value=await promise;if(!Array.isArray(value.items)||!(value.nextCursor===null||typeof value.nextCursor==="string")||value.items.some(item=>!item||!UUID.test(item.id)||typeof item.displayName!=="string"))throw new TutorCvApiError("INVALID_RESPONSE",500);return value};
  return Object.freeze({ getMyTutorCv:()=>profileResponse(request("/api/v1/me/tutor-cv",{authenticated:true})), saveMyTutorCv:(profile,expectedVersion)=>profileResponse(request("/api/v1/me/tutor-cv",{method:"PUT",body:{profile,expectedVersion},authenticated:true})), publishMyTutorCv:(expectedVersion)=>profileResponse(request("/api/v1/me/tutor-cv/publish",{method:"POST",body:{expectedVersion},authenticated:true})), unpublishMyTutorCv:(expectedVersion)=>profileResponse(request("/api/v1/me/tutor-cv/unpublish",{method:"POST",body:{expectedVersion},authenticated:true})), listTutors:(filters)=>listResponse(request(`/api/v1/tutors${query(filters)}`)), getTutor:(id)=>{if(!UUID.test(id))return Promise.reject(new TutorCvApiError("INVALID_TUTOR_ID",400));return profileResponse(request(`/api/v1/tutors/${encodeURIComponent(id)}`))} });
}
