-- Tutor-provided public CVs. Publication is not verification.
do $$ begin create type public.tutor_publication_status as enum ('draft','published','unpublished'); exception when duplicate_object then null; end $$;
do $$ begin create type public.teaching_format as enum ('online','in_person','both'); exception when duplicate_object then null; end $$;
do $$ begin create type public.language_proficiency as enum ('basic','conversational','professional','native'); exception when duplicate_object then null; end $$;

create table if not exists public.subjects (id bigint generated always as identity primary key, slug text not null unique, display_name text not null, active boolean not null default true, sort_order integer not null default 0, check (slug ~ '^[a-z0-9-]{1,64}$'), check (char_length(btrim(display_name)) between 1 and 80));
create table if not exists public.regions (id bigint generated always as identity primary key, slug text not null unique, display_name text not null, active boolean not null default true, sort_order integer not null default 0, check (slug ~ '^[a-z0-9-]{1,64}$'), check (char_length(btrim(display_name)) between 1 and 80));
insert into public.subjects(slug,display_name,sort_order) values ('mathematics','Mathematics',1),('english','English',2),('physics','Physics',3),('chemistry','Chemistry',4),('literature','Literature',5),('ielts','IELTS',6),('computer-science','Computer Science',7) on conflict(slug) do nothing;
insert into public.regions(slug,display_name,sort_order) values ('district-1','District 1',1),('district-3','District 3',2),('district-7','District 7',3),('binh-thanh','Binh Thanh',4),('thu-duc','Thu Duc',5) on conflict(slug) do nothing;

create table if not exists public.tutor_profiles (
 id uuid primary key default gen_random_uuid(), user_id uuid not null unique references public.profiles(id) on delete cascade,
 display_name text not null, headline text, bio text, hourly_rate_vnd bigint, currency text not null default 'VND', teaching_format public.teaching_format,
 avatar_object_path text, publication_status public.tutor_publication_status not null default 'draft', published_at timestamptz, unpublished_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), version bigint not null default 1,
 check (display_name=btrim(display_name) and char_length(display_name) between 1 and 80), check(headline is null or (headline=btrim(headline) and char_length(headline)<=120)),
 check(bio is null or (bio=btrim(bio) and char_length(bio)<=2000)), check(hourly_rate_vnd is null or hourly_rate_vnd between 50000 and 10000000), check(currency='VND'),
 check(avatar_object_path is null or char_length(avatar_object_path)<=512), check(version>0)
);
create table if not exists public.tutor_subjects (tutor_profile_id uuid references public.tutor_profiles(id) on delete cascade, subject_id bigint references public.subjects(id), primary key(tutor_profile_id,subject_id));
create table if not exists public.tutor_levels (tutor_profile_id uuid references public.tutor_profiles(id) on delete cascade, level_code text, primary key(tutor_profile_id,level_code), check(level_code in ('primary','lower_secondary','upper_secondary','university','adult','beginner','intermediate','advanced','exam_preparation')));
create table if not exists public.tutor_regions (tutor_profile_id uuid references public.tutor_profiles(id) on delete cascade, region_id bigint references public.regions(id), primary key(tutor_profile_id,region_id));
create table if not exists public.tutor_languages (id uuid primary key default gen_random_uuid(), tutor_profile_id uuid not null references public.tutor_profiles(id) on delete cascade, language_code text not null, display_name text not null, proficiency public.language_proficiency not null, unique(tutor_profile_id,language_code), check(char_length(btrim(language_code)) between 1 and 16),check(char_length(btrim(display_name)) between 1 and 60));
create table if not exists public.tutor_availability_slots (id uuid primary key default gen_random_uuid(),tutor_profile_id uuid not null references public.tutor_profiles(id) on delete cascade,day_of_week integer not null,start_time time not null,end_time time not null,timezone text not null,created_at timestamptz not null default now(),unique(tutor_profile_id,day_of_week,start_time,end_time),check(day_of_week between 0 and 6),check(start_time<end_time),check(char_length(btrim(timezone)) between 1 and 64));
create table if not exists public.tutor_education_entries (id uuid primary key default gen_random_uuid(),tutor_profile_id uuid not null references public.tutor_profiles(id) on delete cascade,institution text not null,qualification text not null,field_of_study text not null default '',start_year integer not null,end_year integer,description text not null default '',sort_order integer not null,check(char_length(btrim(institution)) between 1 and 120),check(char_length(btrim(qualification)) between 1 and 120),check(char_length(field_of_study)<=120),check(char_length(description)<=500),check(start_year between 1900 and 2100),check(end_year is null or end_year between start_year and 2100));
create table if not exists public.tutor_experience_entries (id uuid primary key default gen_random_uuid(),tutor_profile_id uuid not null references public.tutor_profiles(id) on delete cascade,title text not null,organization text not null,start_year integer not null,end_year integer,description text not null default '',sort_order integer not null,check(char_length(btrim(title)) between 1 and 120),check(char_length(btrim(organization)) between 1 and 120),check(char_length(description)<=700),check(start_year between 1900 and 2100),check(end_year is null or end_year between start_year and 2100));
create table if not exists public.tutor_profile_events (id bigint generated always as identity primary key,tutor_profile_id uuid not null references public.tutor_profiles(id) on delete cascade,actor_user_id uuid not null references public.profiles(id) on delete cascade,event_type text not null,profile_version bigint not null,safe_metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),check(event_type in ('created','draft_saved','published','published_profile_updated','unpublished','avatar_changed','avatar_removed')),check(jsonb_typeof(safe_metadata)='object'));
create index if not exists tutor_profiles_public_order on public.tutor_profiles(published_at desc,id desc) where publication_status='published';
create index if not exists tutor_subjects_subject on public.tutor_subjects(subject_id,tutor_profile_id); create index if not exists tutor_regions_region on public.tutor_regions(region_id,tutor_profile_id);

create or replace function public.tutor_text_has_contact(value text) returns boolean language sql immutable set search_path='' as $$ select coalesce(value,'') ~* '(https?://|www\.|[[:alnum:]._%+-]+[[:space:]]*@[[:space:]]*[[:alnum:].-]+\.[[:alpha:]]{2,}|(^|[^[:digit:]])(\+?[[:digit:]][[:space:]().-]*){8,15}([^[:digit:]]|$)|(^|[[:space:]])@[[:alnum:]_.]{3,}|zalo|whats[[:space:]]*app|telegram|contact[[:space:]]+me[[:space:]]+at|liên[[:space:]]*hệ|bit\.ly|tinyurl\.com|t\.me|wa\.me|verified tutor|identity verified|credentials verified|approved by tutoria|certified by tutoria|background checked)' $$;
revoke all on function public.tutor_text_has_contact(text) from public,anon,authenticated;
create or replace function public.assert_tutor_caller() returns uuid language plpgsql security definer set search_path='' as $$ declare uid uuid:=auth.uid(); begin if uid is null then raise insufficient_privilege; end if; if not exists(select 1 from public.profiles where id=uid and role='tutor') then raise insufficient_privilege; end if; return uid; end $$;
revoke all on function public.assert_tutor_caller() from public,anon,authenticated;

create or replace function public.tutor_cv_json(pid uuid, include_private boolean default false) returns jsonb language sql stable security definer set search_path='' as $$
select jsonb_build_object('id',p.id,'displayName',p.display_name,'headline',p.headline,'bio',p.bio,'hourlyRateVnd',p.hourly_rate_vnd,'currency',p.currency,'teachingFormat',p.teaching_format,
 'subjects',coalesce((select jsonb_agg(s.slug order by s.sort_order,s.slug) from public.tutor_subjects x join public.subjects s on s.id=x.subject_id where x.tutor_profile_id=p.id),'[]'::jsonb),
 'levels',coalesce((select jsonb_agg(x.level_code order by x.level_code) from public.tutor_levels x where x.tutor_profile_id=p.id),'[]'::jsonb),
 'regions',coalesce((select jsonb_agg(r.slug order by r.sort_order,r.slug) from public.tutor_regions x join public.regions r on r.id=x.region_id where x.tutor_profile_id=p.id),'[]'::jsonb),
 'languages',coalesce((select jsonb_agg(jsonb_build_object('code',x.language_code,'displayName',x.display_name,'proficiency',x.proficiency) order by x.language_code) from public.tutor_languages x where x.tutor_profile_id=p.id),'[]'::jsonb),
 'availability',coalesce((select jsonb_agg(jsonb_build_object('dayOfWeek',x.day_of_week,'startTime',to_char(x.start_time,'HH24:MI'),'endTime',to_char(x.end_time,'HH24:MI'),'timezone',x.timezone) order by x.day_of_week,x.start_time) from public.tutor_availability_slots x where x.tutor_profile_id=p.id),'[]'::jsonb),
 'education',coalesce((select jsonb_agg(jsonb_build_object('institution',x.institution,'qualification',x.qualification,'fieldOfStudy',x.field_of_study,'startYear',x.start_year,'endYear',x.end_year,'description',x.description) order by x.sort_order) from public.tutor_education_entries x where x.tutor_profile_id=p.id),'[]'::jsonb),
 'experience',coalesce((select jsonb_agg(jsonb_build_object('title',x.title,'organization',x.organization,'startYear',x.start_year,'endYear',x.end_year,'description',x.description) order by x.sort_order) from public.tutor_experience_entries x where x.tutor_profile_id=p.id),'[]'::jsonb),
 'avatarUrl',case when p.avatar_object_path is null then null else current_setting('app.settings.avatar_public_base_url',true)||'/'||p.avatar_object_path end,
 'publicationStatus',case when include_private then to_jsonb(p.publication_status) else null end,'publishedAt',p.published_at,'updatedAt',case when include_private then p.updated_at else null end,'version',case when include_private then p.version else null end)
from public.tutor_profiles p where p.id=pid $$;
revoke all on function public.tutor_cv_json(uuid,boolean) from public,anon,authenticated;

create or replace function public.get_my_tutor_cv() returns jsonb language plpgsql security definer set search_path='' as $$ declare uid uuid:=public.assert_tutor_caller(); pid uuid; begin select id into pid from public.tutor_profiles where user_id=uid; if pid is null then return null; end if; return public.tutor_cv_json(pid,true); end $$;
create or replace function public.tutor_cv_publishable(pid uuid) returns boolean language sql stable security definer set search_path='' as $$ select char_length(coalesce(p.headline,'')) between 10 and 120 and char_length(coalesce(p.bio,'')) between 100 and 2000 and p.hourly_rate_vnd between 50000 and 10000000 and p.teaching_format is not null and exists(select 1 from public.tutor_subjects x join public.subjects s on s.id=x.subject_id where x.tutor_profile_id=p.id and s.active) and exists(select 1 from public.tutor_levels x where x.tutor_profile_id=p.id) and exists(select 1 from public.tutor_languages x where x.tutor_profile_id=p.id) and exists(select 1 from public.tutor_availability_slots x where x.tutor_profile_id=p.id) and (p.teaching_format='online' or exists(select 1 from public.tutor_regions x join public.regions r on r.id=x.region_id where x.tutor_profile_id=p.id and r.active)) from public.tutor_profiles p where p.id=pid $$;
create or replace function public.save_my_tutor_cv(payload jsonb,expected_version bigint) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=public.assert_tutor_caller(); pid uuid; old_status public.tutor_publication_status; new_version bigint; item jsonb; n integer; allowed text[]:=array['displayName','headline','bio','hourlyRateVnd','currency','teachingFormat','subjects','levels','regions','languages','availability','education','experience'];
begin
 if payload is null or jsonb_typeof(payload)<>'object' or exists(select 1 from jsonb_object_keys(payload) k where not(k=any(allowed))) then raise exception 'TUTOR_CV_INVALID' using errcode='22023'; end if;
 if public.tutor_text_has_contact(payload->>'displayName') or public.tutor_text_has_contact(payload->>'headline') or public.tutor_text_has_contact(payload->>'bio') or public.tutor_text_has_contact(payload->>'education') or public.tutor_text_has_contact(payload->>'experience') then raise exception 'CONTACT_INFORMATION_NOT_ALLOWED' using errcode='22023'; end if;
 if coalesce(jsonb_array_length(payload->'subjects'),0)>10 or coalesce(jsonb_array_length(payload->'levels'),0)>10 or coalesce(jsonb_array_length(payload->'regions'),0)>20 or coalesce(jsonb_array_length(payload->'languages'),0)>8 or coalesce(jsonb_array_length(payload->'availability'),0)>28 or coalesce(jsonb_array_length(payload->'education'),0)>5 or coalesce(jsonb_array_length(payload->'experience'),0)>10 then raise exception 'TUTOR_CV_INVALID' using errcode='22023'; end if;
 select id,publication_status into pid,old_status from public.tutor_profiles where user_id=uid for update;
 if pid is null then if expected_version is not null then raise exception 'PROFILE_VERSION_CONFLICT' using errcode='40001'; end if; insert into public.tutor_profiles(user_id,display_name,headline,bio,hourly_rate_vnd,currency,teaching_format) values(uid,btrim(payload->>'displayName'),nullif(btrim(payload->>'headline'),''),nullif(btrim(payload->>'bio'),''),(payload->>'hourlyRateVnd')::bigint,coalesce(payload->>'currency','VND'),(payload->>'teachingFormat')::public.teaching_format) returning id,publication_status,version into pid,old_status,new_version; insert into public.tutor_profile_events(tutor_profile_id,actor_user_id,event_type,profile_version) values(pid,uid,'created',new_version);
 else if expected_version is null or (select version from public.tutor_profiles where id=pid)<>expected_version then raise exception 'PROFILE_VERSION_CONFLICT' using errcode='40001'; end if; update public.tutor_profiles set display_name=btrim(payload->>'displayName'),headline=nullif(btrim(payload->>'headline'),''),bio=nullif(btrim(payload->>'bio'),''),hourly_rate_vnd=(payload->>'hourlyRateVnd')::bigint,currency=payload->>'currency',teaching_format=(payload->>'teachingFormat')::public.teaching_format,updated_at=now(),version=version+1 where id=pid returning version into new_version; end if;
 delete from public.tutor_subjects where tutor_profile_id=pid; insert into public.tutor_subjects select pid,s.id from jsonb_array_elements_text(payload->'subjects') v join public.subjects s on s.slug=v.value; if (select count(*) from public.tutor_subjects where tutor_profile_id=pid)<>jsonb_array_length(payload->'subjects') then raise exception 'TUTOR_CV_INVALID' using errcode='22023'; end if;
 delete from public.tutor_levels where tutor_profile_id=pid; insert into public.tutor_levels select pid,value from jsonb_array_elements_text(payload->'levels');
 delete from public.tutor_regions where tutor_profile_id=pid; insert into public.tutor_regions select pid,r.id from jsonb_array_elements_text(payload->'regions') v join public.regions r on r.slug=v.value; if (select count(*) from public.tutor_regions where tutor_profile_id=pid)<>jsonb_array_length(payload->'regions') then raise exception 'TUTOR_CV_INVALID' using errcode='22023'; end if;
 delete from public.tutor_languages where tutor_profile_id=pid; for item in select * from jsonb_array_elements(payload->'languages') loop insert into public.tutor_languages(tutor_profile_id,language_code,display_name,proficiency) values(pid,btrim(item->>'code'),btrim(item->>'displayName'),(item->>'proficiency')::public.language_proficiency); end loop;
 delete from public.tutor_availability_slots where tutor_profile_id=pid; for item in select * from jsonb_array_elements(payload->'availability') loop if exists(select 1 from public.tutor_availability_slots where tutor_profile_id=pid and day_of_week=(item->>'dayOfWeek')::int and start_time<(item->>'endTime')::time and end_time>(item->>'startTime')::time) then raise exception 'TUTOR_CV_INVALID' using errcode='22023'; end if; insert into public.tutor_availability_slots(tutor_profile_id,day_of_week,start_time,end_time,timezone) values(pid,(item->>'dayOfWeek')::int,(item->>'startTime')::time,(item->>'endTime')::time,btrim(item->>'timezone')); end loop;
 delete from public.tutor_education_entries where tutor_profile_id=pid; n:=0; for item in select * from jsonb_array_elements(payload->'education') loop insert into public.tutor_education_entries(tutor_profile_id,institution,qualification,field_of_study,start_year,end_year,description,sort_order) values(pid,btrim(item->>'institution'),btrim(item->>'qualification'),coalesce(btrim(item->>'fieldOfStudy'),''),(item->>'startYear')::int,(item->>'endYear')::int,coalesce(btrim(item->>'description'),''),n); n:=n+1; end loop;
 delete from public.tutor_experience_entries where tutor_profile_id=pid; n:=0; for item in select * from jsonb_array_elements(payload->'experience') loop insert into public.tutor_experience_entries(tutor_profile_id,title,organization,start_year,end_year,description,sort_order) values(pid,btrim(item->>'title'),btrim(item->>'organization'),(item->>'startYear')::int,(item->>'endYear')::int,coalesce(btrim(item->>'description'),''),n); n:=n+1; end loop;
 if old_status='published' and not public.tutor_cv_publishable(pid) then raise exception 'TUTOR_CV_INCOMPLETE' using errcode='22023'; end if;
 insert into public.tutor_profile_events(tutor_profile_id,actor_user_id,event_type,profile_version) values(pid,uid,case when old_status='published' then 'published_profile_updated' else 'draft_saved' end,new_version); return public.tutor_cv_json(pid,true);
end $$;

create or replace function public.tutor_cv_publishable(pid uuid) returns boolean language sql stable security definer set search_path='' as $$ select char_length(coalesce(p.headline,'')) between 10 and 120 and char_length(coalesce(p.bio,'')) between 100 and 2000 and p.hourly_rate_vnd between 50000 and 10000000 and p.teaching_format is not null and exists(select 1 from public.tutor_subjects x join public.subjects s on s.id=x.subject_id where x.tutor_profile_id=p.id and s.active) and exists(select 1 from public.tutor_levels x where x.tutor_profile_id=p.id) and exists(select 1 from public.tutor_languages x where x.tutor_profile_id=p.id) and exists(select 1 from public.tutor_availability_slots x where x.tutor_profile_id=p.id) and (p.teaching_format='online' or exists(select 1 from public.tutor_regions x join public.regions r on r.id=x.region_id where x.tutor_profile_id=p.id and r.active)) from public.tutor_profiles p where p.id=pid $$;
create or replace function public.publish_my_tutor_cv(expected_version bigint) returns jsonb language plpgsql security definer set search_path='' as $$ declare uid uuid:=public.assert_tutor_caller(); pid uuid; v bigint; begin select id,version into pid,v from public.tutor_profiles where user_id=uid for update; if pid is null then raise no_data_found; end if; if v<>expected_version then raise exception 'PROFILE_VERSION_CONFLICT' using errcode='40001'; end if; if not public.tutor_cv_publishable(pid) then raise exception 'TUTOR_CV_INCOMPLETE' using errcode='22023'; end if; update public.tutor_profiles set publication_status='published',published_at=now(),unpublished_at=null,updated_at=now(),version=version+1 where id=pid returning version into v; insert into public.tutor_profile_events(tutor_profile_id,actor_user_id,event_type,profile_version) values(pid,uid,'published',v); return public.tutor_cv_json(pid,true); end $$;
create or replace function public.unpublish_my_tutor_cv(expected_version bigint) returns jsonb language plpgsql security definer set search_path='' as $$ declare uid uuid:=public.assert_tutor_caller(); pid uuid; v bigint; begin select id,version into pid,v from public.tutor_profiles where user_id=uid for update; if pid is null then raise no_data_found; end if; if v<>expected_version then raise exception 'PROFILE_VERSION_CONFLICT' using errcode='40001'; end if; update public.tutor_profiles set publication_status='unpublished',unpublished_at=now(),updated_at=now(),version=version+1 where id=pid returning version into v; insert into public.tutor_profile_events(tutor_profile_id,actor_user_id,event_type,profile_version) values(pid,uid,'unpublished',v); return public.tutor_cv_json(pid,true); end $$;

create or replace function public.get_published_tutor(tutor_profile_id uuid) returns jsonb language sql stable security definer set search_path='' as $$ select public.tutor_cv_json(p.id,false)-'publicationStatus'-'updatedAt'-'version' from public.tutor_profiles p where p.id=tutor_profile_id and p.publication_status='published' $$;
create or replace function public.list_published_tutors(filters jsonb default '{}'::jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$ declare lim int:=least(coalesce((filters->>'limit')::int,12),24); cur_ts timestamptz; cur_id uuid; rows jsonb; next_cur text; has_more boolean; last_ts timestamptz; last_id uuid; begin
 if exists(select 1 from jsonb_object_keys(filters) k where k not in ('subject','level','region','format','minRate','maxRate','cursor','limit')) then raise exception 'TUTOR_CV_INVALID' using errcode='22023'; end if;
 if filters?'cursor' then begin select convert_from(decode(filters->>'cursor','base64'),'utf8')::jsonb->>0,(convert_from(decode(filters->>'cursor','base64'),'utf8')::jsonb->>1)::uuid into cur_ts,cur_id; exception when others then raise exception 'TUTOR_CV_INVALID' using errcode='22023'; end; end if;
 with q as (select p.* from public.tutor_profiles p where p.publication_status='published' and (cur_ts is null or (p.published_at,p.id)<(cur_ts,cur_id)) and (not(filters?'format') or p.teaching_format=(filters->>'format')::public.teaching_format) and (not(filters?'minRate') or p.hourly_rate_vnd>=(filters->>'minRate')::bigint) and (not(filters?'maxRate') or p.hourly_rate_vnd<=(filters->>'maxRate')::bigint) and (not(filters?'subject') or exists(select 1 from public.tutor_subjects x join public.subjects s on s.id=x.subject_id where x.tutor_profile_id=p.id and s.active and s.slug=filters->>'subject')) and (not(filters?'level') or exists(select 1 from public.tutor_levels x where x.tutor_profile_id=p.id and x.level_code=filters->>'level')) and (not(filters?'region') or exists(select 1 from public.tutor_regions x join public.regions r on r.id=x.region_id where x.tutor_profile_id=p.id and r.active and r.slug=filters->>'region')) order by p.published_at desc,p.id desc limit lim+1), page as (select * from q limit lim)
 select coalesce((select jsonb_agg((public.tutor_cv_json(id,false)-'bio')||jsonb_build_object('bioExcerpt',left(bio,240)) order by published_at desc,id desc) from page),'[]'::jsonb),exists(select 1 from q offset lim),(select published_at from page offset lim-1 limit 1),(select id from page offset lim-1 limit 1) into rows,has_more,last_ts,last_id;
 if has_more then next_cur:=encode(convert_to(jsonb_build_array(last_ts,last_id)::text,'utf8'),'base64'); end if; return jsonb_build_object('items',rows,'nextCursor',next_cur); end $$;

do $$ declare t text; begin foreach t in array array['tutor_profiles','subjects','regions','tutor_subjects','tutor_levels','tutor_regions','tutor_languages','tutor_availability_slots','tutor_education_entries','tutor_experience_entries','tutor_profile_events'] loop execute format('alter table public.%I enable row level security',t); execute format('revoke all on table public.%I from public,anon,authenticated',t); end loop; end $$;
revoke all on function public.get_my_tutor_cv(),public.save_my_tutor_cv(jsonb,bigint),public.publish_my_tutor_cv(bigint),public.unpublish_my_tutor_cv(bigint),public.list_published_tutors(jsonb),public.get_published_tutor(uuid),public.tutor_cv_publishable(uuid),public.tutor_cv_json(uuid,boolean) from public,anon,authenticated;
grant execute on function public.get_my_tutor_cv(),public.save_my_tutor_cv(jsonb,bigint),public.publish_my_tutor_cv(bigint),public.unpublish_my_tutor_cv(bigint) to authenticated;
grant execute on function public.list_published_tutors(jsonb),public.get_published_tutor(uuid) to anon,authenticated;
