import { describe,expect,it,vi } from "vitest"; import { createTutorCvApi } from "../../src/api/tutor-cv-api.js";
const json=(body,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}}));
describe("tutor CV API",()=>{
 it("sends owner tokens only for private endpoints",async()=>{const fetchImpl=vi.fn(()=>json({ok:true,profile:null}));const api=createTutorCvApi({apiBaseUrl:"https://api.test",getAccessToken:()=>"token",fetchImpl});await api.getMyTutorCv();expect(fetchImpl.mock.calls[0][1].headers.Authorization).toBe("Bearer token");expect(fetchImpl.mock.calls[0][1].credentials).toBe("omit")});
 it("never sends auth on public tutor listing",async()=>{const fetchImpl=vi.fn(()=>json({ok:true,items:[],nextCursor:null}));const api=createTutorCvApi({apiBaseUrl:"https://api.test",getAccessToken:()=>"token",fetchImpl});await api.listTutors({subject:"math & science",limit:12});expect(fetchImpl.mock.calls[0][0]).toContain("subject=math+%26+science");expect(fetchImpl.mock.calls[0][1].headers.Authorization).toBeUndefined()});
 it("does not retry mutations",async()=>{const fetchImpl=vi.fn(()=>json({ok:false,error:{code:"PROFILE_VERSION_CONFLICT"}},409));const api=createTutorCvApi({apiBaseUrl:"https://api.test",getAccessToken:()=>"token",fetchImpl});await expect(api.publishMyTutorCv(2)).rejects.toMatchObject({code:"PROFILE_VERSION_CONFLICT",status:409});expect(fetchImpl).toHaveBeenCalledTimes(1)});
 it("rejects invalid public IDs before fetch",async()=>{const fetchImpl=vi.fn();const api=createTutorCvApi({apiBaseUrl:"",getAccessToken:()=>null,fetchImpl});await expect(api.getTutor("demo-id")).rejects.toMatchObject({code:"INVALID_TUTOR_ID"});expect(fetchImpl).not.toHaveBeenCalled()});
 it("fails closed on malformed responses",async()=>{const api=createTutorCvApi({apiBaseUrl:"",getAccessToken:()=>null,fetchImpl:()=>json({items:[]})});await expect(api.listTutors({})).rejects.toMatchObject({code:"INVALID_RESPONSE"})});
});
