import { randomUUID } from "node:crypto"; import { readFile } from "node:fs/promises"; import { fileURLToPath } from "node:url"; import { createClient } from "@supabase/supabase-js"; import postgres from "postgres"; import { beforeAll,describe,expect,it } from "vitest"; import { signUpConfirmed } from "./auth-helpers.js";
const url=process.env.SUPABASE_TEST_URL,key=process.env.SUPABASE_TEST_PUBLISHABLE_KEY,dbUrl=process.env.SUPABASE_TEST_DB_URL,serviceKey=process.env.SUPABASE_TEST_SERVICE_ROLE_KEY;
if(!url||!key||!dbUrl||!serviceKey)throw new Error("Integration tests require local Supabase URL, publishable key, DB URL, and service role key.");
if(!["localhost","127.0.0.1","host.docker.internal"].includes(new URL(url).hostname))throw new Error("Refusing to run integration tests against a non-local Supabase target.");
const anon=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),sql=postgres(dbUrl,{max:4}),password="Local-test-only-Password1!";
async function signup(role:"student"|"tutor"){const email=`cc-${randomUUID()}@example.test`;return signUpConfirmed({anon,url:url!,publishableKey:key!,serviceRoleKey:serviceKey!,email,password,metadata:{name:"Concurrency",role}})}
const FUTURE={startsAt:new Date(Date.now()+2*3600e3).toISOString(),endsAt:new Date(Date.now()+3*3600e3).toISOString()};
async function createSession(tutor:any,o:any={}){return tutor.client.rpc("create_session",{payload:{...FUTURE,...o}})}
async function reserved(sid:string){const rows=await sql`select coalesce(sum(participant_count),0)::int as n from public.bookings where session_id=${sid} and status in ('requested','confirmed')`;return rows[0].n}
describe.sequential("sessions + bookings concurrency invariants",()=>{
 beforeAll(async()=>{ for(const n of ["0001_create_profiles.sql","0004_create_sessions_and_bookings.sql","0005_create_booking_session_rpcs.sql","0006_create_event_outbox.sql","0007_emit_domain_events_from_booking_session_rpcs.sql"]){const m=await readFile(fileURLToPath(new URL(`../supabase/migrations/${n}`,import.meta.url)),"utf8");await sql.unsafe(m)}});
 it("1. last-seat race: exactly one concurrent booking wins",async()=>{const tutor=await signup("tutor");const l1=await signup("student");const l2=await signup("student");const s=await createSession(tutor,{maxParticipants:1});const results=await Promise.all([l1.client.rpc("create_booking",{session_id:s.data.id,participant_count:1}),l2.client.rpc("create_booking",{session_id:s.data.id,participant_count:1})]);expect(results.filter(r=>!r.error)).toHaveLength(1);const failed=results.find(r=>r.error);expect(failed!.error!.message).toContain("INSUFFICIENT_CAPACITY");expect(await reserved(s.data.id)).toBe(1)});
 it("2. capacity-neutral confirm: seat stays hard-reserved",async()=>{const tutor=await signup("tutor");const l1=await signup("student");const l2=await signup("student");const s=await createSession(tutor,{maxParticipants:1});const b=await l1.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});await tutor.client.rpc("confirm_booking",{booking_id:b.data.id,expected_version:b.data.version});expect(await reserved(s.data.id)).toBe(1);expect((await l2.client.rpc("create_booking",{session_id:s.data.id,participant_count:1})).error?.message).toContain("INSUFFICIENT_CAPACITY")});
 it("3. confirm vs session-cancel race: no confirmed booking survives a cancelled session",async()=>{const tutor=await signup("tutor");const l=await signup("student");const s=await createSession(tutor,{maxParticipants:2});const b=await l.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});const sv=(await anon.rpc("get_session",{sid:s.data.id})).data.version;await Promise.all([tutor.client.rpc("confirm_booking",{booking_id:b.data.id,expected_version:b.data.version}),tutor.client.rpc("cancel_session",{sid:s.data.id,expected_version:sv,cause:"host"})]);const row=(await sql`select b.status as bstatus, s.status as sstatus from public.bookings b join public.sessions s on s.id=b.session_id where b.id=${b.data.id}`)[0];expect(row.sstatus).toBe("cancelled");expect(row.bstatus).toBe("cancelled");expect(await reserved(s.data.id)).toBe(0)});
 it("4. create vs capacity-reduction race: committed state never exceeds max",async()=>{const tutor=await signup("tutor");const l1=await signup("student");const l2=await signup("student");const s=await createSession(tutor,{maxParticipants:3});await l1.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});const sv=(await anon.rpc("get_session",{sid:s.data.id})).data.version;const [book2,capChange]=await Promise.all([l2.client.rpc("create_booking",{session_id:s.data.id,participant_count:1}),tutor.client.rpc("change_session_capacity",{sid:s.data.id,new_max:1,expected_version:sv})]);expect(Boolean(book2.error)).not.toEqual(Boolean(capChange.error));const maxRow=(await sql`select max_participants from public.sessions where id=${s.data.id}`)[0];expect(await reserved(s.data.id)).toBeLessThanOrEqual(maxRow.max_participants)});
 it("5a. reschedule accept fails atomically when the target is full",async()=>{const tutor=await signup("tutor");const l1=await signup("student");const l2=await signup("student");const a=await createSession(tutor,{maxParticipants:1});const b=await createSession(tutor,{maxParticipants:1});const ba=await l1.client.rpc("create_booking",{session_id:a.data.id,participant_count:1});await l2.client.rpc("create_booking",{session_id:b.data.id,participant_count:1});const req=await l1.client.rpc("create_reschedule_request",{booking_id:ba.data.id,target_session_id:b.data.id,expected_version:ba.data.version});expect(req.error).toBeNull();const acc=await tutor.client.rpc("accept_reschedule_request",{request_id:req.data.id});expect(acc.error?.message).toContain("INSUFFICIENT_CAPACITY");const row=(await sql`select session_id from public.bookings where id=${ba.data.id}`)[0];expect(row.session_id).toBe(a.data.id);expect(await reserved(a.data.id)).toBe(1);expect(await reserved(b.data.id)).toBe(1)});
 it("5b. reschedule accept fails atomically on target uniqueness conflict",async()=>{const tutor=await signup("tutor");const l=await signup("student");const a=await createSession(tutor,{maxParticipants:1});const d=await createSession(tutor,{maxParticipants:2});const ba=await l.client.rpc("create_booking",{session_id:a.data.id,participant_count:1});await l.client.rpc("create_booking",{session_id:d.data.id,participant_count:1});const req=await l.client.rpc("create_reschedule_request",{booking_id:ba.data.id,target_session_id:d.data.id,expected_version:ba.data.version});const acc=await tutor.client.rpc("accept_reschedule_request",{request_id:req.data.id});expect(acc.error?.message).toContain("BOOKING_CONFLICT");const row=(await sql`select session_id from public.bookings where id=${ba.data.id}`)[0];expect(row.session_id).toBe(a.data.id);expect(await reserved(a.data.id)).toBe(1);expect(await reserved(d.data.id)).toBe(1)});
 it("5c. reschedule accept moves the booking and swaps which seat is free",async()=>{const tutor=await signup("tutor");const l=await signup("student");const e=await createSession(tutor,{maxParticipants:1});const f=await createSession(tutor,{maxParticipants:1});const b=await l.client.rpc("create_booking",{session_id:e.data.id,participant_count:1});const req=await l.client.rpc("create_reschedule_request",{booking_id:b.data.id,target_session_id:f.data.id,expected_version:b.data.version});const acc=await tutor.client.rpc("accept_reschedule_request",{request_id:req.data.id});expect(acc.error).toBeNull();const row=(await sql`select session_id,rescheduled_from_session_id from public.bookings where id=${b.data.id}`)[0];expect(row.session_id).toBe(f.data.id);expect(row.rescheduled_from_session_id).toBe(e.data.id);expect(await reserved(e.data.id)).toBe(0);expect(await reserved(f.data.id)).toBe(1)});
 it("5d. duplicate pending reschedule for the same booking is rejected",async()=>{const tutor=await signup("tutor");const l=await signup("student");const e=await createSession(tutor,{maxParticipants:2});const f=await createSession(tutor,{maxParticipants:2});const g=await createSession(tutor,{maxParticipants:2});const b=await l.client.rpc("create_booking",{session_id:e.data.id,participant_count:1});await l.client.rpc("create_reschedule_request",{booking_id:b.data.id,target_session_id:f.data.id,expected_version:b.data.version});const dup=await l.client.rpc("create_reschedule_request",{booking_id:b.data.id,target_session_id:g.data.id,expected_version:b.data.version});expect(dup.error?.message).toContain("BOOKING_CONFLICT");expect((await sql`select count(*)::int as n from public.reschedule_requests where booking_id=${b.data.id} and status='requested'`)[0].n).toBe(1)});
});
