import { randomUUID } from "node:crypto"; import { readFile } from "node:fs/promises"; import { fileURLToPath } from "node:url"; import { createClient } from "@supabase/supabase-js"; import postgres from "postgres"; import { afterAll, beforeAll, describe, expect, it } from "vitest"; import { signUpConfirmed } from "./auth-helpers.js";import { makeOffering } from "./_fixtures/offering.js";
const url=process.env.SUPABASE_TEST_URL,key=process.env.SUPABASE_TEST_PUBLISHABLE_KEY,dbUrl=process.env.SUPABASE_TEST_DB_URL,serviceKey=process.env.SUPABASE_TEST_SERVICE_ROLE_KEY;
if(!url||!key||!dbUrl||!serviceKey)throw new Error("Integration tests require local Supabase URL, publishable key, DB URL, and service role key.");
if(!["localhost","127.0.0.1","host.docker.internal"].includes(new URL(url).hostname))throw new Error("Refusing to run integration tests against a non-local Supabase target.");
const anon=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),sql=postgres(dbUrl,{max:4}),password="Local-test-only-Password1!";
async function signup(role:"student"|"tutor"){const email=`sb-${randomUUID()}@example.test`;return signUpConfirmed({anon,url:url!,publishableKey:key!,serviceRoleKey:serviceKey!,email,password,metadata:{name:"Sess Booking",role},trustedTutor:role==="tutor"})}
const FUTURE={startsAt:new Date(Date.now()+2*3600e3).toISOString(),endsAt:new Date(Date.now()+3*3600e3).toISOString()};
const PAST={startsAt:new Date(Date.now()-3*3600e3).toISOString(),endsAt:new Date(Date.now()-2*3600e3).toISOString()};
async function createSession(tutor:any,o:any={}){const offeringId=await makeOffering(tutor.client,tutor.user.id,"workshop");return tutor.client.rpc("create_session",{payload:{offeringId,...FUTURE,...o}})}
async function reserved(sid:string){const rows=await sql`select coalesce(sum(participant_count),0)::int as n from public.bookings where session_id=${sid} and status in ('requested','confirmed')`;return rows[0].n}
describe.sequential("sessions + bookings RLS, authorization, CAS, uniqueness",()=>{
 beforeAll(async()=>{ for(const n of ["0001_create_profiles.sql","0004_create_sessions_and_bookings.sql","0005_create_booking_session_rpcs.sql","0006_create_event_outbox.sql","0007_emit_domain_events_from_booking_session_rpcs.sql"]){const m=await readFile(fileURLToPath(new URL(`../supabase/migrations/${n}`,import.meta.url)),"utf8");await sql.unsafe(m)} await sql`drop function if exists public.create_booking(uuid, integer)`});
 it("denies direct table access to anon and authenticated",async()=>{const s=await signup("student");for(const t of ["sessions","bookings","reschedule_requests","attendance_facts","booking_history","session_history"]){expect((await s.client.from(t as any).select()).error).toBeTruthy();expect((await s.client.from(t as any).insert({})).error).toBeTruthy()}expect((await anon.from("sessions").select()).error).toBeTruthy()});
 it("requires tutor role to create sessions; students cannot manage host sessions",async()=>{const tutor=await signup("tutor");const learner=await signup("student");const created=await createSession(tutor,{maxParticipants:2});expect(created.error).toBeNull();expect(created.data.status).toBe("scheduled");expect(created.data).not.toHaveProperty("hostId");expect((await createSession(learner)).error).toBeTruthy();expect((await learner.client.rpc("cancel_session",{sid:created.data.id,expected_version:1})).error).toBeTruthy();expect((await learner.client.rpc("reschedule_session",{sid:created.data.id,startsAt:FUTURE.startsAt,endsAt:FUTURE.endsAt,expected_version:1})).error).toBeTruthy();expect((await learner.client.rpc("change_session_capacity",{sid:created.data.id,new_max:2,expected_version:1})).error).toBeTruthy();expect((await learner.client.rpc("complete_session",{sid:created.data.id,expected_version:1})).error).toBeTruthy()});
 it("learners cannot confirm; host confirms; capacity-neutral confirm keeps seat hard-reserved",async()=>{const tutor=await signup("tutor");const l1=await signup("student");const l2=await signup("student");const s=await createSession(tutor,{maxParticipants:1});const b=await l1.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});expect(b.error).toBeNull();expect((await l1.client.rpc("confirm_booking",{booking_id:b.data.id,expected_version:b.data.version})).error).toBeTruthy();const confirmed=await tutor.client.rpc("confirm_booking",{booking_id:b.data.id,expected_version:b.data.version});expect(confirmed.error).toBeNull();expect(confirmed.data.status).toBe("confirmed");expect(await reserved(s.data.id)).toBe(1);const again=await l2.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});expect(again.error?.message).toContain("INSUFFICIENT_CAPACITY")});
 it("rejects stale versions (CAS) with no side effect",async()=>{const tutor=await signup("tutor");const l=await signup("student");const s=await createSession(tutor,{maxParticipants:2});const b=await l.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});const stale=await tutor.client.rpc("confirm_booking",{booking_id:b.data.id,expected_version:b.data.version+1});expect(stale.error?.message).toContain("STALE_VERSION");expect((await sql`select status from public.bookings where id=${b.data.id}`)[0].status).toBe("requested");const ok=await tutor.client.rpc("confirm_booking",{booking_id:b.data.id,expected_version:b.data.version});expect(ok.error).toBeNull();const staleCancel=await l.client.rpc("cancel_booking",{booking_id:b.data.id,expected_version:b.data.version+2});expect(staleCancel.error?.message).toContain("STALE_VERSION")});
 it("enforces one active booking per learner per session",async()=>{const tutor=await signup("tutor");const l=await signup("student");const s=await createSession(tutor,{maxParticipants:3});const b1=await l.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});expect(b1.error).toBeNull();const b2=await l.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});expect(b2.error?.message).toContain("BOOKING_CONFLICT");const cancelled=await l.client.rpc("cancel_booking",{booking_id:b1.data.id,expected_version:b1.data.version});expect(cancelled.error).toBeNull();expect((await l.client.rpc("create_booking",{session_id:s.data.id,participant_count:1})).error).toBeNull()});
 it("releases capacity on reject and on cancel so the seat is reusable",async()=>{const tutor=await signup("tutor");const l=await signup("student");const s=await createSession(tutor,{maxParticipants:1});const b=await l.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});const rejected=await tutor.client.rpc("reject_booking",{booking_id:b.data.id,expected_version:b.data.version});expect(rejected.error).toBeNull();expect(await reserved(s.data.id)).toBe(0);const b2=await l.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});expect(b2.error).toBeNull();const confirmed=await tutor.client.rpc("confirm_booking",{booking_id:b2.data.id,expected_version:b2.data.version});const cancelled=await l.client.rpc("cancel_booking",{booking_id:b2.data.id,expected_version:confirmed.data.version});expect(cancelled.error).toBeNull();expect(await reserved(s.data.id)).toBe(0);expect((await l.client.rpc("create_booking",{session_id:s.data.id,participant_count:1})).error).toBeNull()});
 it("host cannot cancel a requested booking directly; learner withdraws and host cancels confirmed",async()=>{const tutor=await signup("tutor");const l=await signup("student");const s=await createSession(tutor,{maxParticipants:2});const b=await l.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});expect((await tutor.client.rpc("cancel_booking",{booking_id:b.data.id,expected_version:b.data.version,cause:"host"})).error?.message).toContain("INVALID_TRANSITION");const confirmed=await tutor.client.rpc("confirm_booking",{booking_id:b.data.id,expected_version:b.data.version});const byHost=await tutor.client.rpc("cancel_booking",{booking_id:b.data.id,expected_version:confirmed.data.version,cause:"host"});expect(byHost.error).toBeNull();expect((await sql`select status,cancelled_by from public.bookings where id=${b.data.id}`)[0].cancelled_by).toBe("host")});
 it("completes bookings after the session ends and records attendance facts",async()=>{const tutor=await signup("tutor");const l=await signup("student");const s=await createSession(tutor,{...PAST,maxParticipants:2});const b=await l.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});const confirmed=await tutor.client.rpc("confirm_booking",{booking_id:b.data.id,expected_version:b.data.version});expect(confirmed.error).toBeNull();const sd=await tutor.client.rpc("complete_session",{sid:s.data.id,expected_version:s.data.version});expect(sd.error).toBeNull();const done=await l.client.rpc("complete_booking",{booking_id:b.data.id,expected_version:confirmed.data.version});expect(done.error).toBeNull();expect(done.data.status).toBe("completed");const facts=await sql`select outcome,reported_by from public.attendance_facts where booking_id=${b.data.id}`;expect(facts[0].outcome).toBe("attended");expect(facts[0].reported_by).toBe("attendee")});
 it("host records learner no-show; re-report after terminal state is rejected",async()=>{const tutor=await signup("tutor");const l=await signup("student");const s=await createSession(tutor,{...PAST,maxParticipants:2});const b=await l.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});const confirmed=await tutor.client.rpc("confirm_booking",{booking_id:b.data.id,expected_version:b.data.version});const r1=await tutor.client.rpc("record_attendance",{booking_id:b.data.id,outcome:"learner_no_show",expected_version:confirmed.data.version});expect(r1.error).toBeNull();expect((await sql`select status from public.bookings where id=${b.data.id}`)[0].status).toBe("cancelled");expect((await sql`select outcome from public.attendance_facts where booking_id=${b.data.id}`)[0].outcome).toBe("learner_no_show");expect((await tutor.client.rpc("record_attendance",{booking_id:b.data.id,outcome:"learner_no_show",expected_version:confirmed.data.version+1})).error?.message).toContain("INVALID_TRANSITION")});
 it("keeps public session payload private and scopes reads",async()=>{const tutor=await signup("tutor");const l1=await signup("student");const l2=await signup("student");const s=await createSession(tutor,{maxParticipants:5});const b=await l1.client.rpc("create_booking",{session_id:s.data.id,participant_count:1});const listed=await anon.rpc("list_sessions");expect(JSON.stringify(listed.data)).not.toMatch(/host_id|learner_id|"email"|"phone"/i);const got=await anon.rpc("get_session",{sid:s.data.id});expect(got.data.hardReservedCapacity).toBe(1);expect(got.data.spotsLeft).toBe(4);expect(got.data).not.toHaveProperty("hostId");expect((await l2.client.rpc("get_booking",{bid:b.data.id})).error).toBeTruthy();expect((await l1.client.rpc("get_booking",{bid:b.data.id})).error).toBeNull();const mine=await l2.client.rpc("get_my_bookings");expect(JSON.stringify(mine.data)).toBe("null")});
});
afterAll(async () => { await sql.end(); });
