import { randomUUID } from "node:crypto"; import { readFile } from "node:fs/promises"; import { fileURLToPath } from "node:url"; import { createClient } from "@supabase/supabase-js"; import postgres from "postgres"; import { beforeAll,describe,expect,it } from "vitest"; import { signUpConfirmed } from "./auth-helpers.js";
const url=process.env.SUPABASE_TEST_URL,key=process.env.SUPABASE_TEST_PUBLISHABLE_KEY,dbUrl=process.env.SUPABASE_TEST_DB_URL,serviceKey=process.env.SUPABASE_TEST_SERVICE_ROLE_KEY;
if(!url||!key||!dbUrl||!serviceKey)throw new Error("Integration tests require local Supabase URL, publishable key, DB URL, and service role key.");
if(!["localhost","127.0.0.1","host.docker.internal"].includes(new URL(url).hostname))throw new Error("Refusing to run integration tests against a non-local Supabase target.");
const anon=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),sql=postgres(dbUrl,{max:1}),password="Local-test-only-Password1!";
async function signup(role:"student"|"tutor"){const email=`cv-${randomUUID()}@example.test`;return signUpConfirmed({anon,url:url!,publishableKey:key!,serviceRoleKey:serviceKey!,email,password,metadata:{name:"CV Test",role},trustedTutor:role==="tutor"})}
const complete={displayName:"Nguyen Minh Anh",headline:"Mathematics tutor",bio:"I provide patient and structured mathematics lessons with clear examples and practice for secondary students.",hourlyRateVnd:300000,currency:"VND",teachingFormat:"online",subjects:["mathematics"],levels:["lower_secondary"],regions:[],languages:[{code:"vi",displayName:"Vietnamese",proficiency:"native"}],availability:[{dayOfWeek:1,startTime:"18:00",endTime:"20:00",timezone:"Asia/Ho_Chi_Minh"}],education:[],experience:[]};
describe.sequential("local tutor CV RPC and RLS",()=>{
 beforeAll(async()=>{for(const name of ["0001_create_profiles.sql","0002_create_tutor_cvs.sql"]){const migration=await readFile(fileURLToPath(new URL(`../supabase/migrations/${name}`,import.meta.url)),"utf8");await sql.unsafe(migration)}});
 it("denies students and direct writes",async()=>{const s=await signup("student");expect((await s.client.rpc("save_my_tutor_cv",{payload:complete,expected_version:null})).error).toBeTruthy();expect((await s.client.from("tutor_profiles").insert({user_id:s.user.id,display_name:"X"})).error).toBeTruthy()});
 it("creates, publishes, lists, and unpublishes only the owner profile",async()=>{const t=await signup("tutor");const saved=await t.client.rpc("save_my_tutor_cv",{payload:complete,expected_version:null});expect(saved.error).toBeNull();expect(saved.data).not.toHaveProperty("user_id");const published=await t.client.rpc("publish_my_tutor_cv",{expected_version:saved.data.version});expect(published.error).toBeNull();const listed=await anon.rpc("list_published_tutors",{filters:{limit:12}});expect(listed.data.items.some((v:any)=>v.id===published.data.id)).toBe(true);expect(JSON.stringify(listed.data)).not.toMatch(/user_id|email|phone|avatar_object_path/);const unpublished=await t.client.rpc("unpublish_my_tutor_cv",{expected_version:published.data.version});expect(unpublished.error).toBeNull();expect((await anon.rpc("get_published_tutor",{tutor_profile_id:published.data.id})).data).toBeNull();expect((await t.client.rpc("get_my_tutor_cv")).data.publicationStatus).toBe("unpublished")});
 it.each(["Tutor at tutor@example.com","Call 0901 234 567","See https://example.com"])("rejects contact information: %s",async bio=>{const t=await signup("tutor");const result=await t.client.rpc("save_my_tutor_cv",{payload:{...complete,bio},expected_version:null});expect(result.error).toBeTruthy()});
 it("rejects stale versions without partial child replacement",async()=>{const t=await signup("tutor");const saved=await t.client.rpc("save_my_tutor_cv",{payload:complete,expected_version:null});const stale=await t.client.rpc("save_my_tutor_cv",{payload:{...complete,subjects:["english"]},expected_version:saved.data.version+1});expect(stale.error).toBeTruthy();expect((await t.client.rpc("get_my_tutor_cv")).data.subjects).toEqual(["mathematics"])});
});
